name: Build

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: 
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ko
        uses: imjasonh/setup-ko@v0.6
        with:
          version: v0.12.0
        env: 
          KO_DOCKER_REPO: docker.io/brandond
      - env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          echo "${AUTH_TOKEN}" | ko login docker.io --username brandond --password-stdin
          [[ ${GITHUB_REF} =~ refs/heads ]] && export TAGS=latest
          [[ ${GITHUB_REF} =~ refs/tags ]] && export TAGS=latest,${GITHUB_REF/refs\/tags\//}
          ko build --platform=linux/amd64,linux/arm64,linux/arm/v7 --tags ${TAGS}
